# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# dbt_snowflake: Change directory to where dbt project is located
# deps: Run dbt dependencies to install packages used in dbt project

name: Snowflake-DBT-CI-Dev

trigger:
    branches:
        include:
        - Development

pool:
  vmImage: 'ubuntu-latest'

container: 
  image: python:3.7
  options: -u root

steps:

- task: DownloadSecureFile@1
  name: SettingProfile
  displayName: 'Downloading Profile for Snowflake'
  inputs:
    secureFile: 'profiles.yml'

- script: |
    echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
    mkdir ~/.dbt
    cp $(SettingProfile.secureFilePath) ~/.dbt/profiles.yml
  displayName: Installing Profile for Snowflake
    
- script: |
    pip install dbt --user
    export PATH=$PATH:/home/vsts_azpcontainer/.local/bin
    cd dbt_snowflake
    dbt deps
    dbt compile
    dbt test
    dbt run --full-refresh
    dbt test
  displayName: 'Compile, Test, and Run'